2023-07-20 18:40:04.180234 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 18:41:22.305476 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 18:47:15.602871 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 18:47:40.019834 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 18:50:12.064293 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 18:50:20.743352 >>> SweFAQ
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 99, in evaluate
    ndcg, _map, recall, precision = retriever.evaluate(relevant_docs, results, retriever.k_values)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/beir/retrieval/evaluation.py", line 73, in evaluate
    evaluator = pytrec_eval.RelevanceEvaluator(qrels, {map_string, ndcg_string, recall_string, precision_string})
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/pytrec_eval/__init__.py", line 59, in __init__
    super().__init__(query_relevance=query_relevance, measures=measures, relevance_level=relevance_level)
TypeError: Expected relevance to be integer.


2023-07-20 18:50:30.902508 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 18:50:39.343365 >>> SweFAQ
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 99, in evaluate
    ndcg, _map, recall, precision = retriever.evaluate(relevant_docs, results, retriever.k_values)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/beir/retrieval/evaluation.py", line 73, in evaluate
    evaluator = pytrec_eval.RelevanceEvaluator(qrels, {map_string, ndcg_string, recall_string, precision_string})
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/pytrec_eval/__init__.py", line 59, in __init__
    super().__init__(query_relevance=query_relevance, measures=measures, relevance_level=relevance_level)
TypeError: Expected relevance to be integer.


2023-07-20 18:51:25.700148 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 18:51:34.730060 >>> SweFAQ
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 99, in evaluate
    ndcg, _map, recall, precision = retriever.evaluate(relevant_docs, results, retriever.k_values)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/beir/retrieval/evaluation.py", line 73, in evaluate
    evaluator = pytrec_eval.RelevanceEvaluator(qrels, {map_string, ndcg_string, recall_string, precision_string})
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/pytrec_eval/__init__.py", line 59, in __init__
    super().__init__(query_relevance=query_relevance, measures=measures, relevance_level=relevance_level)
TypeError: Expected relevance to be integer.


2023-07-20 18:51:43.491940 >>> SweFAQ
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 99, in evaluate
    ndcg, _map, recall, precision = retriever.evaluate(relevant_docs, results, retriever.k_values)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/beir/retrieval/evaluation.py", line 73, in evaluate
    evaluator = pytrec_eval.RelevanceEvaluator(qrels, {map_string, ndcg_string, recall_string, precision_string})
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/pytrec_eval/__init__.py", line 59, in __init__
    super().__init__(query_relevance=query_relevance, measures=measures, relevance_level=relevance_level)
TypeError: Expected relevance to be integer.


2023-07-20 18:52:31.548396 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 18:52:32.087296 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 18:52:47.049922 >>> SweFAQ
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 99, in evaluate
    ndcg, _map, recall, precision = retriever.evaluate(relevant_docs, results, retriever.k_values)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/beir/retrieval/evaluation.py", line 73, in evaluate
    evaluator = pytrec_eval.RelevanceEvaluator(qrels, {map_string, ndcg_string, recall_string, precision_string})
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/pytrec_eval/__init__.py", line 59, in __init__
    super().__init__(query_relevance=query_relevance, measures=measures, relevance_level=relevance_level)
TypeError: Expected relevance to be integer.


2023-07-20 18:52:47.394154 >>> SweFAQ
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 99, in evaluate
    ndcg, _map, recall, precision = retriever.evaluate(relevant_docs, results, retriever.k_values)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/beir/retrieval/evaluation.py", line 73, in evaluate
    evaluator = pytrec_eval.RelevanceEvaluator(qrels, {map_string, ndcg_string, recall_string, precision_string})
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/pytrec_eval/__init__.py", line 59, in __init__
    super().__init__(query_relevance=query_relevance, measures=measures, relevance_level=relevance_level)
TypeError: Expected relevance to be integer.


2023-07-20 18:53:00.027345 >>> SweFAQ
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 99, in evaluate
    ndcg, _map, recall, precision = retriever.evaluate(relevant_docs, results, retriever.k_values)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/beir/retrieval/evaluation.py", line 73, in evaluate
    evaluator = pytrec_eval.RelevanceEvaluator(qrels, {map_string, ndcg_string, recall_string, precision_string})
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/pytrec_eval/__init__.py", line 59, in __init__
    super().__init__(query_relevance=query_relevance, measures=measures, relevance_level=relevance_level)
TypeError: Expected relevance to be integer.


2023-07-20 18:53:00.051549 >>> SweFAQ
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 99, in evaluate
    ndcg, _map, recall, precision = retriever.evaluate(relevant_docs, results, retriever.k_values)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/beir/retrieval/evaluation.py", line 73, in evaluate
    evaluator = pytrec_eval.RelevanceEvaluator(qrels, {map_string, ndcg_string, recall_string, precision_string})
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/pytrec_eval/__init__.py", line 59, in __init__
    super().__init__(query_relevance=query_relevance, measures=measures, relevance_level=relevance_level)
TypeError: Expected relevance to be integer.


2023-07-20 18:54:15.694131 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 19:02:49.500055 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 19:50:57.634371 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 19:51:46.921186 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 20:02:29.448363 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 20:20:03.927841 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 65, in _evaluate_monolingual
    eval_split = dataset[eval_split]
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'


2023-07-20 21:22:47.298281 >>> DKHateClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 93, in _evaluate_monolingual
    scores_exp, test_cache = evaluator(model, test_cache=test_cache)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/evaluators/ClassificationEvaluator.py", line 227, in __call__
    X_test = np.asarray(model.encode(self.sentences_test, batch_size=self.batch_size))
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 165, in encode
    out_features = self.forward(features)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 74, in forward
    output_states = self.auto_model(**trans_features, return_dict=False)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 839, in forward
    embedding_output = self.embeddings(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 131, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self


2023-07-20 21:22:50.503988 >>> DanishPoliticalCommentsClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 93, in _evaluate_monolingual
    scores_exp, test_cache = evaluator(model, test_cache=test_cache)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/evaluators/ClassificationEvaluator.py", line 227, in __call__
    X_test = np.asarray(model.encode(self.sentences_test, batch_size=self.batch_size))
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 165, in encode
    out_features = self.forward(features)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 74, in forward
    output_states = self.auto_model(**trans_features, return_dict=False)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 839, in forward
    embedding_output = self.embeddings(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 131, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self


2023-07-20 21:22:52.389585 >>> NorwegianParliament
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 93, in _evaluate_monolingual
    scores_exp, test_cache = evaluator(model, test_cache=test_cache)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/evaluators/ClassificationEvaluator.py", line 224, in __call__
    X_train = np.asarray(model.encode(self.sentences_train, batch_size=self.batch_size))
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 165, in encode
    out_features = self.forward(features)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 74, in forward
    output_states = self.auto_model(**trans_features, return_dict=False)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 839, in forward
    embedding_output = self.embeddings(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 131, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self


2023-07-20 21:24:37.412737 >>> SwerecClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 58, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTaskClassification.py", line 93, in _evaluate_monolingual
    scores_exp, test_cache = evaluator(model, test_cache=test_cache)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/evaluators/ClassificationEvaluator.py", line 227, in __call__
    X_test = np.asarray(model.encode(self.sentences_test, batch_size=self.batch_size))
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 165, in encode
    out_features = self.forward(features)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 74, in forward
    output_states = self.auto_model(**trans_features, return_dict=False)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 839, in forward
    embedding_output = self.embeddings(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 131, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self


2023-07-21 05:16:11.601590 >>> ScalaNbClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 225, in run
    task.load_data(eval_splits=task_eval_splits)
  File "/Users/au561649/Github/mteb/tasks.py", line 290, in load_data
    self.dataset = datasets.load_dataset(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1785, in load_dataset
    builder_instance = load_dataset_builder(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1514, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1231, in dataset_module_factory
    raise e1 from None
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1187, in dataset_module_factory
    raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({type(e).__name__})")
ConnectionError: Couldn't reach 'ScandEval/scala-nb' on the Hub (ConnectionError)


2023-07-21 05:34:09.788830 >>> ScalaNbClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 225, in run
    task.load_data(eval_splits=task_eval_splits)
  File "/Users/au561649/Github/mteb/tasks.py", line 326, in load_data
    self.dataset = datasets.load_dataset(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1785, in load_dataset
    builder_instance = load_dataset_builder(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1514, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1231, in dataset_module_factory
    raise e1 from None
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1215, in dataset_module_factory
    ).get_module()
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 771, in get_module
    hfh_dataset_info = HfApi(config.HF_ENDPOINT).dataset_info(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1740, in dataset_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), '(Request ID: a0fe534f-272d-4d06-94be-37c9a6c8ce85)')


2023-07-21 08:33:06.393751 >>> ScalaSvClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 225, in run
    task.load_data(eval_splits=task_eval_splits)
  File "/Users/au561649/Github/mteb/tasks.py", line 362, in load_data
    self.dataset = datasets.load_dataset(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1785, in load_dataset
    builder_instance = load_dataset_builder(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1514, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1231, in dataset_module_factory
    raise e1 from None
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1198, in dataset_module_factory
    raise e
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1172, in dataset_module_factory
    dataset_info = hf_api.dataset_info(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1740, in dataset_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=100.0)"), '(Request ID: d5f83dbe-e025-42a2-9d65-1f4846b45d10)')


2023-07-21 13:22:02.981631 >>> NoRecClassification
Traceback (most recent call last):
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 225, in run
    task.load_data(eval_splits=task_eval_splits)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/mteb/abstasks/AbsTask.py", line 31, in load_data
    self.dataset = datasets.load_dataset(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1785, in load_dataset
    builder_instance = load_dataset_builder(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1514, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1231, in dataset_module_factory
    raise e1 from None
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1198, in dataset_module_factory
    raise e
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/datasets/load.py", line 1172, in dataset_module_factory
    dataset_info = hf_api.dataset_info(
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1740, in dataset_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/Users/au561649/.virtualenvs/mteb_test/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=100.0)"), '(Request ID: ffbf2e50-5dfc-4ae0-a0b5-8db89d320aec)')


